<?php
 /**
  * Title: Project
  * Slug: gutenify-construction/project
  * Categories: gutenify-construction
  */
?>
<!-- wp:group {"align":"full","className":"gutenify-section-f976df30-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","right":"var:preset|spacing|40","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40"}}},"backgroundColor":"background","layout":{"inherit":true,"type":"constrained"}} -->
<div class="wp-block-group alignfull gutenify-section-f976df30-ffa4-11ed-88c9-09be3b957db8 has-background-background-color has-background" style="padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"align":"wide","className":"gutenify-section-f9641a80-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"blockGap":"10px","padding":{"bottom":"3px"}}},"layout":{"inherit":false}} -->
<div class="wp-block-group alignwide gutenify-section-f9641a80-ffa4-11ed-88c9-09be3b957db8" style="padding-bottom:3px"><!-- wp:group {"className":"gutenify-section-f963cc60-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"blockGap":"10px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group gutenify-section-f963cc60-ffa4-11ed-88c9-09be3b957db8"><!-- wp:paragraph {"align":"center","className":"animated animated-fadeInUp gutenify-section-f96293e0-ffa4-11ed-88c9-09be3b957db8","style":{"typography":{"letterSpacing":"0px","fontStyle":"normal","fontWeight":"600"}},"textColor":"primary","fontSize":"normal"} -->
<p class="has-text-align-center animated animated-fadeInUp gutenify-section-f96293e0-ffa4-11ed-88c9-09be3b957db8 has-primary-color has-text-color has-normal-font-size" style="font-style:normal;font-weight:600;letter-spacing:0px"><?php echo esc_html__( 'OUR PROJECT', 'gutenify-construction' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"textAlign":"center","className":"animated animated-fadeInUp gutenify-section-f9630910-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"margin":{"bottom":"14px"}},"typography":{"textTransform":"capitalize","lineHeight":"1.3","fontStyle":"normal","fontWeight":"700"}},"textColor":"foreground","fontSize":"huge"} -->
<h2 class="wp-block-heading has-text-align-center animated animated-fadeInUp gutenify-section-f9630910-ffa4-11ed-88c9-09be3b957db8 has-foreground-color has-text-color has-huge-font-size" style="margin-bottom:14px;font-style:normal;font-weight:700;line-height:1.3;text-transform:capitalize"><?php echo esc_html__( 'See The Ideas &amp; Visions For Industries!', 'gutenify-construction' ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:columns {"align":"wide","className":"gutenify-section-f9755890-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"blockGap":{"top":"40px","left":"40px"}}}} -->
<div class="wp-block-columns alignwide gutenify-section-f9755890-ffa4-11ed-88c9-09be3b957db8"><!-- wp:column {"className":"gutenify-section-f966d9a0-ffa4-11ed-88c9-09be3b957db8","style":{"color":{"background":"#ffb25900"}}} -->
<div class="wp-block-column gutenify-section-f966d9a0-ffa4-11ed-88c9-09be3b957db8 has-background" style="background-color:#ffb25900"><!-- wp:group {"className":"has-shadow-dark animated animated-fadeInUp gutenify-section-f9668b80-ffa4-11ed-88c9-09be3b957db8","style":{"border":{"radius":"0px","width":"0px","style":"none"},"spacing":{"padding":{"top":"0px","bottom":"0px","right":"0px","left":"0px"},"blockGap":"0px"}},"textColor":"background","layout":{"contentSize":""}} -->
<div class="wp-block-group has-shadow-dark animated animated-fadeInUp gutenify-section-f9668b80-ffa4-11ed-88c9-09be3b957db8 has-background-color has-text-color" style="border-style:none;border-width:0px;border-radius:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:cover {"url":"https://demo.gutenify.com/gutenify-civil/wp-content/themes/gutenify-civil/images/wwd-1.jpg","id":765,"dimRatio":80,"minHeight":611,"minHeightUnit":"px","customGradient":"linear-gradient(0deg,rgb(3,3,3) 6%,rgba(0,0,0,0) 56%)","contentPosition":"bottom center","className":"gutenify-section-f9661650-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-cover has-custom-content-position is-position-bottom-center gutenify-section-f9661650-ffa4-11ed-88c9-09be3b957db8" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0;min-height:611px"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-80 has-background-dim wp-block-cover__gradient-background has-background-gradient" style="background:linear-gradient(0deg,rgb(3,3,3) 6%,rgba(0,0,0,0) 56%)"></span><img class="wp-block-cover__image-background wp-image-765" alt="" src="https://demo.gutenify.com/gutenify-civil/wp-content/themes/gutenify-civil/images/wwd-1.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"gutenify-section-f964ddd0-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"blockGap":"0","padding":{"top":"var:preset|spacing|10","right":"var:preset|spacing|20","bottom":"var:preset|spacing|10","left":"var:preset|spacing|20"}}},"backgroundColor":"background","layout":{"type":"constrained"}} -->
<div class="wp-block-group gutenify-section-f964ddd0-ffa4-11ed-88c9-09be3b957db8 has-background-background-color has-background" style="padding-top:var(--wp--preset--spacing--10);padding-right:var(--wp--preset--spacing--20);padding-bottom:var(--wp--preset--spacing--10);padding-left:var(--wp--preset--spacing--20)"><!-- wp:heading {"textAlign":"left","level":3,"className":"gutenify-section-f9648fb0-ffa4-11ed-88c9-09be3b957db8","style":{"typography":{"textTransform":"capitalize","fontStyle":"normal","fontWeight":"600"},"elements":{"link":{"color":{"text":"var:preset|color|foreground"}}}},"fontSize":"medium"} -->
<h3 class="wp-block-heading has-text-align-left gutenify-section-f9648fb0-ffa4-11ed-88c9-09be3b957db8 has-link-color has-medium-font-size" style="font-style:normal;font-weight:600;text-transform:capitalize"><a href="#"><?php echo esc_html__( 'Building Renovation', 'gutenify-construction' ); ?></a></h3>
<!-- /wp:heading --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"className":"gutenify-section-f974bc50-ffa4-11ed-88c9-09be3b957db8","style":{"color":{"background":"#ffb25900"},"spacing":{"blockGap":"40px"}}} -->
<div class="wp-block-column gutenify-section-f974bc50-ffa4-11ed-88c9-09be3b957db8 has-background" style="background-color:#ffb25900"><!-- wp:columns {"align":"wide","className":"gutenify-section-f96d4240-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"},"blockGap":{"top":"40px","left":"40px"}}}} -->
<div class="wp-block-columns alignwide gutenify-section-f96d4240-ffa4-11ed-88c9-09be3b957db8" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:column {"className":"gutenify-section-f969e6e0-ffa4-11ed-88c9-09be3b957db8","style":{"color":{"background":"#ffb25900"}}} -->
<div class="wp-block-column gutenify-section-f969e6e0-ffa4-11ed-88c9-09be3b957db8 has-background" style="background-color:#ffb25900"><!-- wp:group {"className":"has-shadow-dark animated animated-fadeInUp gutenify-section-f96998c0-ffa4-11ed-88c9-09be3b957db8","style":{"border":{"radius":"0px","width":"0px","style":"none"},"spacing":{"padding":{"top":"0px","bottom":"0px","right":"0px","left":"0px"},"blockGap":"0px"}},"textColor":"background","layout":{"contentSize":""}} -->
<div class="wp-block-group has-shadow-dark animated animated-fadeInUp gutenify-section-f96998c0-ffa4-11ed-88c9-09be3b957db8 has-background-color has-text-color" style="border-style:none;border-width:0px;border-radius:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:cover {"url":"https://demo.gutenify.com/gutenify-civil/wp-content/themes/gutenify-civil/images/wwd-2.jpg","id":713,"dimRatio":70,"minHeight":279,"minHeightUnit":"px","customGradient":"linear-gradient(0deg,rgb(3,3,3) 6%,rgba(0,0,0,0) 56%)","contentPosition":"bottom center","className":"gutenify-section-f968d570-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-cover has-custom-content-position is-position-bottom-center gutenify-section-f968d570-ffa4-11ed-88c9-09be3b957db8" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0;min-height:279px"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-70 has-background-dim wp-block-cover__gradient-background has-background-gradient" style="background:linear-gradient(0deg,rgb(3,3,3) 6%,rgba(0,0,0,0) 56%)"></span><img class="wp-block-cover__image-background wp-image-713" alt="" src="https://demo.gutenify.com/gutenify-civil/wp-content/themes/gutenify-civil/images/wwd-2.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"gutenify-section-f967c400-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"padding":{"top":"15px","right":"30px","bottom":"13px","left":"30px"}},"elements":{"link":{"color":{"text":"var:preset|color|foreground"}}}},"backgroundColor":"background","layout":{"type":"constrained"}} -->
<div class="wp-block-group gutenify-section-f967c400-ffa4-11ed-88c9-09be3b957db8 has-background-background-color has-background has-link-color" style="padding-top:15px;padding-right:30px;padding-bottom:13px;padding-left:30px"><!-- wp:heading {"textAlign":"left","level":3,"className":"gutenify-section-f9674ed0-ffa4-11ed-88c9-09be3b957db8","style":{"typography":{"textTransform":"capitalize","fontStyle":"normal","fontWeight":"600","fontSize":"18px"},"elements":{"link":{"color":{"text":"var:preset|color|foreground"}}}}} -->
<h3 class="wp-block-heading has-text-align-left gutenify-section-f9674ed0-ffa4-11ed-88c9-09be3b957db8 has-link-color" style="font-size:18px;font-style:normal;font-weight:600;text-transform:capitalize"><a href="#"><?php echo esc_html__( 'Architectural Design', 'gutenify-construction' ); ?></a></h3>
<!-- /wp:heading --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"className":"gutenify-section-f96ccd10-ffa4-11ed-88c9-09be3b957db8","style":{"color":{"background":"#ffb25900"}}} -->
<div class="wp-block-column gutenify-section-f96ccd10-ffa4-11ed-88c9-09be3b957db8 has-background" style="background-color:#ffb25900"><!-- wp:group {"className":"has-shadow-dark animated animated-fadeInUp gutenify-section-f96c7ef0-ffa4-11ed-88c9-09be3b957db8","style":{"border":{"radius":"0px","width":"0px","style":"none"},"spacing":{"padding":{"top":"0px","bottom":"0px","right":"0px","left":"0px"},"blockGap":"0px"}},"textColor":"background","layout":{"contentSize":""}} -->
<div class="wp-block-group has-shadow-dark animated animated-fadeInUp gutenify-section-f96c7ef0-ffa4-11ed-88c9-09be3b957db8 has-background-color has-text-color" style="border-style:none;border-width:0px;border-radius:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:cover {"url":"https://demo.gutenify.com/gutenify-civil/wp-content/themes/gutenify-civil/images/wwd-3.jpg","id":766,"dimRatio":80,"focalPoint":{"x":0.73,"y":0.58},"minHeight":279,"minHeightUnit":"px","customGradient":"linear-gradient(0deg,rgb(3,3,3) 6%,rgba(0,0,0,0) 56%)","contentPosition":"bottom center","className":"gutenify-section-f96c09c0-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-cover has-custom-content-position is-position-bottom-center gutenify-section-f96c09c0-ffa4-11ed-88c9-09be3b957db8" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0;min-height:279px"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-80 has-background-dim wp-block-cover__gradient-background has-background-gradient" style="background:linear-gradient(0deg,rgb(3,3,3) 6%,rgba(0,0,0,0) 56%)"></span><img class="wp-block-cover__image-background wp-image-766" alt="" src="https://demo.gutenify.com/gutenify-civil/wp-content/themes/gutenify-civil/images/wwd-3.jpg" style="object-position:73% 58%" data-object-fit="cover" data-object-position="73% 58%"/><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"gutenify-section-f96ad140-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"padding":{"top":"15px","right":"30px","bottom":"15px","left":"30px"}},"elements":{"link":{"color":{"text":"var:preset|color|foreground"}}}},"backgroundColor":"background","layout":{"type":"constrained"}} -->
<div class="wp-block-group gutenify-section-f96ad140-ffa4-11ed-88c9-09be3b957db8 has-background-background-color has-background has-link-color" style="padding-top:15px;padding-right:30px;padding-bottom:15px;padding-left:30px"><!-- wp:heading {"textAlign":"left","level":3,"className":"gutenify-section-f96a5c10-ffa4-11ed-88c9-09be3b957db8","style":{"typography":{"textTransform":"capitalize","fontStyle":"normal","fontWeight":"600","fontSize":"18px"},"elements":{"link":{"color":{"text":"var:preset|color|foreground"}}}}} -->
<h3 class="wp-block-heading has-text-align-left gutenify-section-f96a5c10-ffa4-11ed-88c9-09be3b957db8 has-link-color" style="font-size:18px;font-style:normal;font-weight:600;text-transform:capitalize"><a href="#"><?php echo esc_html__( 'Low cost housing', 'gutenify-construction' ); ?></a></h3>
<!-- /wp:heading --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns {"align":"wide","className":"gutenify-section-f9744720-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"blockGap":{"top":"40px","left":"40px"}}}} -->
<div class="wp-block-columns alignwide gutenify-section-f9744720-ffa4-11ed-88c9-09be3b957db8"><!-- wp:column {"className":"gutenify-section-f970c4b0-ffa4-11ed-88c9-09be3b957db8","style":{"color":{"background":"#ffb25900"}}} -->
<div class="wp-block-column gutenify-section-f970c4b0-ffa4-11ed-88c9-09be3b957db8 has-background" style="background-color:#ffb25900"><!-- wp:group {"className":"has-shadow-dark animated animated-fadeInUp gutenify-section-f9707690-ffa4-11ed-88c9-09be3b957db8","style":{"border":{"radius":"0px","width":"0px","style":"none"},"spacing":{"padding":{"top":"0px","bottom":"0px","right":"0px","left":"0px"},"blockGap":"0px"}},"textColor":"background","layout":{"contentSize":""}} -->
<div class="wp-block-group has-shadow-dark animated animated-fadeInUp gutenify-section-f9707690-ffa4-11ed-88c9-09be3b957db8 has-background-color has-text-color" style="border-style:none;border-width:0px;border-radius:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:cover {"url":"https://demo.gutenify.com/gutenify-civil/wp-content/themes/gutenify-civil/images/wwd-4.jpg","id":772,"dimRatio":50,"focalPoint":{"x":0.16,"y":0.4},"minHeight":281,"minHeightUnit":"px","customGradient":"linear-gradient(0deg,rgb(3,3,3) 6%,rgba(0,0,0,0) 56%)","contentPosition":"bottom center","className":"gutenify-section-f96fda50-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-cover has-custom-content-position is-position-bottom-center gutenify-section-f96fda50-ffa4-11ed-88c9-09be3b957db8" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0;min-height:281px"><span aria-hidden="true" class="wp-block-cover__background has-background-dim wp-block-cover__gradient-background has-background-gradient" style="background:linear-gradient(0deg,rgb(3,3,3) 6%,rgba(0,0,0,0) 56%)"></span><img class="wp-block-cover__image-background wp-image-772" alt="" src="https://demo.gutenify.com/gutenify-civil/wp-content/themes/gutenify-civil/images/wwd-4.jpg" style="object-position:16% 40%" data-object-fit="cover" data-object-position="16% 40%"/><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"gutenify-section-f96e7ac0-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"padding":{"top":"15px","right":"30px","bottom":"15px","left":"30px"}},"elements":{"link":{"color":{"text":"var:preset|color|foreground"}}}},"backgroundColor":"background","layout":{"type":"constrained"}} -->
<div class="wp-block-group gutenify-section-f96e7ac0-ffa4-11ed-88c9-09be3b957db8 has-background-background-color has-background has-link-color" style="padding-top:15px;padding-right:30px;padding-bottom:15px;padding-left:30px"><!-- wp:heading {"textAlign":"left","level":3,"className":"gutenify-section-f96dde80-ffa4-11ed-88c9-09be3b957db8","style":{"typography":{"textTransform":"capitalize","fontStyle":"normal","fontWeight":"600","fontSize":"18px"},"elements":{"link":{"color":{"text":"var:preset|color|foreground"}}}}} -->
<h3 class="wp-block-heading has-text-align-left gutenify-section-f96dde80-ffa4-11ed-88c9-09be3b957db8 has-link-color" style="font-size:18px;font-style:normal;font-weight:600;text-transform:capitalize"><a href="#"><?php echo esc_html__( 'Foreman Working', 'gutenify-construction' ); ?></a></h3>
<!-- /wp:heading --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"className":"gutenify-section-f973d1f0-ffa4-11ed-88c9-09be3b957db8"} -->
<div class="wp-block-column gutenify-section-f973d1f0-ffa4-11ed-88c9-09be3b957db8"><!-- wp:group {"className":"has-shadow-dark animated animated-fadeInUp gutenify-section-f97383d0-ffa4-11ed-88c9-09be3b957db8","style":{"border":{"radius":"0px","width":"0px","style":"none"},"spacing":{"padding":{"top":"0px","bottom":"0px","right":"0px","left":"0px"},"blockGap":"0px"}},"textColor":"background","layout":{"contentSize":""}} -->
<div class="wp-block-group has-shadow-dark animated animated-fadeInUp gutenify-section-f97383d0-ffa4-11ed-88c9-09be3b957db8 has-background-color has-text-color" style="border-style:none;border-width:0px;border-radius:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:cover {"url":"https://demo.gutenify.com/gutenify-civil/wp-content/themes/gutenify-civil/images/wwd-5.jpg","id":756,"dimRatio":70,"focalPoint":{"x":0.48,"y":0},"minHeight":279,"minHeightUnit":"px","customGradient":"linear-gradient(0deg,rgb(3,3,3) 6%,rgba(0,0,0,0) 56%)","contentPosition":"bottom center","className":"gutenify-section-f9730ea0-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-cover has-custom-content-position is-position-bottom-center gutenify-section-f9730ea0-ffa4-11ed-88c9-09be3b957db8" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0;min-height:279px"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-70 has-background-dim wp-block-cover__gradient-background has-background-gradient" style="background:linear-gradient(0deg,rgb(3,3,3) 6%,rgba(0,0,0,0) 56%)"></span><img class="wp-block-cover__image-background wp-image-756" alt="" src="https://demo.gutenify.com/gutenify-civil/wp-content/themes/gutenify-civil/images/wwd-5.jpg" style="object-position:48% 0%" data-object-fit="cover" data-object-position="48% 0%"/><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"gutenify-section-f971af10-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"padding":{"top":"15px","right":"30px","bottom":"15px","left":"30px"},"blockGap":"0px"},"elements":{"link":{"color":{"text":"var:preset|color|foreground"}}}},"backgroundColor":"background","layout":{"type":"constrained"}} -->
<div class="wp-block-group gutenify-section-f971af10-ffa4-11ed-88c9-09be3b957db8 has-background-background-color has-background has-link-color" style="padding-top:15px;padding-right:30px;padding-bottom:15px;padding-left:30px"><!-- wp:heading {"textAlign":"left","level":3,"className":"gutenify-section-f97139e0-ffa4-11ed-88c9-09be3b957db8","style":{"typography":{"textTransform":"capitalize","fontStyle":"normal","fontWeight":"600","fontSize":"18px"},"elements":{"link":{"color":{"text":"var:preset|color|foreground"}}}}} -->
<h3 class="wp-block-heading has-text-align-left gutenify-section-f97139e0-ffa4-11ed-88c9-09be3b957db8 has-link-color" style="font-size:18px;font-style:normal;font-weight:600;text-transform:capitalize"><a href="#"><?php echo esc_html__( 'Green concrete', 'gutenify-construction' ); ?></a></h3>
<!-- /wp:heading --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:buttons {"className":"animated animated-fadeInUp gutenify-section-f9766a00-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"margin":{"top":"50px","bottom":"0px"}}},"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons animated animated-fadeInUp gutenify-section-f9766a00-ffa4-11ed-88c9-09be3b957db8" style="margin-top:50px;margin-bottom:0px"><!-- wp:button {"className":"is-style-fill gutenify-section-f975f4d0-ffa4-11ed-88c9-09be3b957db8","style":{"spacing":{"padding":{"right":"35px","left":"35px"}}}} -->
<div class="wp-block-button is-style-fill gutenify-section-f975f4d0-ffa4-11ed-88c9-09be3b957db8"><a class="wp-block-button__link wp-element-button" href="#" style="padding-right:35px;padding-left:35px"><?php echo esc_html__( 'View More Projects', 'gutenify-construction' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->